# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Risk Mitigation Strategy Tool            

                                  A QGIS plugin

 Easy-to-use GIS tool to create an operational and practical flood risk mitigation
 strategy for refugee settlements, combining local and global data.

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-11-22
        authors              : Laura Schalbetter and Mona Gaiiring (ETHZ)
        copyright            : UNHCR
        email                : mgairing@ethz.ch
 ***************************************************************************/
"""

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Create an instance of the main plugin class, making in known to QGIS.

    Args:
        iface: A reference to the QGIS interface.

    Returns:
        An instance of the main plugin class.
    """

    from .UNHCR import Main
    return Main(iface)
